module.exports = {
  purge: {
    content: ['./pages/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}'],
    safelist: [
      'focus:ring-offset-indigo-600',
      'lg:border-indigo-400',
      'hover:bg-indigo-500',
      'bg-indigo-600',
      'bg-indigo-700',
      'border-indigo-300',
      'border-indigo-700',
      'text-indigo-200',
      'text-indigo-300',
      'focus:ring-offset-green-600',
      'lg:border-green-400',
      'hover:bg-green-500',
      'bg-green-600',
      'bg-green-700',
      'border-green-300',
      'border-green-700',
      'text-green-200',
      'text-green-300',
      'focus:ring-offset-yellow-600',
      'lg:border-yellow-400',
      'hover:bg-yellow-500',
      'bg-yellow-600',
      'bg-yellow-700',
      'border-yellow-300',
      'border-yellow-700',
      'text-yellow-200',
      'text-yellow-300',
    ],
  },
  darkMode: false,
  theme: {},
  variants: {
    extend: {
      opacity: ['disabled'],
      backgroundColor: ['hover'],
    },
  },
  plugins: [require('@tailwindcss/forms')],
}
